language: c
addons:
  apt:
    packages:
    - libasound2:i386
    - lib32z1
    - lib32bz2-1.0
    - libssl1.0.0:i386
    - libfreetype6:i386
script:
- if [[ ${TRAVIS_BRANCH} == "source" ]]; then make generate; fi
- if [[ ${TRAVIS_BRANCH} == "source" && ${TRAVIS_PULL_REQUEST} == "false" ]]; then make deploy; fi

deploy:
  skip_cleanup: true
env:
  global:
    secure: u8MOq56mbEtWimIUm7V3sn5yMD1Pgrph2DdvUPF8LcTi2u0Gr/phAPeKmCRZ98Aem/0uYDAwC8vNd85DQ6ZbBqqpzZSKLr4I5wc/4VCADGHMSCNENmrXxpqJQHNeoGgxmpnRSu4bESujkH267a1eNO0X7VRDNVMwz6TZUMsm2DxXbAD8jrjSvbjUeljxX2MOquM4v67n93j59K2a86eTKJya9Ptz1hsRLYn+RCZeCgFH3N29/TVf8ZwjylZvH5KoN9AnJjP2bFSFA7k22WSVYM9WCfYhWvi7R8rgum1pjmqjMDZ3PS+tlrS2I97hSc/qSTDf/eoQqcWA4gzRaaCWRs77n8rYNjohgFVOPm3Vs+G7xHUBRpAdoN1nIEHxzZenOvjGXxD4+zmvNHKar8xOs+fbHtX1s0EtSKwR5o14RTiFdBg/TkFOX9APWOHiietpEDxPk16jT15eP4AgqJTw6P9gHn215Q97+7Qaxcr4jbj2ro277WZWxyJkUn7Xajg/aX2k+gi0jZjiKHYZXEFa8JbJDiFZbD8qQFJeyEKdI8DCLXIe7CANk3aXXJpdzrpIkLnP6Flbf3EWABFIxixDqzWxrD5JQh9N05DKRxqrhJS02ueTVVYU4V3RzuRvVwhoVNFUN0yPjtrsFLRqrN5Xy5jkY/fDgqaHSWunjxaz6S0=
